
### 1. Get all nodes

curl -X GET http://localhost:3000/api/nodes


### 2. Get a specific node by ID

curl -X GET http://localhost:3000/api/nodes/1


### 3. Set a node offline (by ID)

curl -X PUT http://localhost:3000/api/nodes/1/offline


### 4. Set a node online (by ID)

curl -X PUT http://localhost:3000/api/nodes/1/online


### 5. Delete a node (by ID)

curl -X DELETE http://localhost:3000/api/nodes/1

